# Generated by Django 5.1.7 on 2025-04-04 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consumer_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispute_type', models.CharField(choices=[('Q', 'Quality Issue'), ('D', 'Delivery Issue'), ('P', 'Payment Issue'), ('O', 'Other')], max_length=1)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('O', 'Open'), ('I', 'In Progress'), ('R', 'Resolved')], default='O', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumer_app.order')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumer_app.consumer')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('F', 'Farmer Verification'), ('O', 'New Order'), ('D', 'Dispute'), ('S', 'System Update')], max_length=1)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
