# Generated by Django 5.1.7 on 2025-04-04 17:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]{10,15}$')], verbose_name='Phone Number')),
                ('village', models.CharField(max_length=100, verbose_name='Village')),
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('state', models.CharField(default='Tamil Nadu', max_length=100, verbose_name='State')),
                ('aadhaar_number', models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{12}$')], verbose_name='Aadhaar Number')),
                ('bank_account', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9]{9,18}$')], verbose_name='Bank Account Number')),
                ('ifsc_code', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[A-Z]{4}0[A-Z0-9]{6}$')], verbose_name='IFSC Code')),
                ('verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Registration Date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farmer',
                'verbose_name_plural': 'Farmers',
            },
        ),
        migrations.CreateModel(
            name='UzhavanHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Hub Name')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('contact_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]{10,15}$')], verbose_name='Contact Number')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('operational_hours', models.CharField(default='6 AM - 6 PM', max_length=100, verbose_name='Operational Hours')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_hubs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uzhavan Hub',
                'verbose_name_plural': 'Uzhavan Hubs',
            },
        ),
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Produce Name')),
                ('category', models.CharField(choices=[('FR', 'Fruits'), ('VE', 'Vegetables'), ('GR', 'Grains'), ('DA', 'Dairy'), ('OT', 'Others')], max_length=2, verbose_name='Category')),
                ('quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Quantity (kg)')),
                ('grade', models.CharField(choices=[('A', 'Grade A - Premium Quality'), ('B', 'Grade B - Good Quality'), ('C', 'Grade C - Standard Quality')], max_length=1, verbose_name='Quality Grade')),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price per kg (₹)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('listed_at', models.DateTimeField(auto_now_add=True, verbose_name='Listed At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('image', models.ImageField(upload_to='produce_images/', verbose_name='Product Image')),
                ('available', models.BooleanField(default=True, verbose_name='Available')),
                ('approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produces', to='uzhavan_hub.farmer')),
                ('hub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hub_produces', to='uzhavan_hub.uzhavanhub')),
            ],
            options={
                'verbose_name': 'Produce',
                'verbose_name_plural': 'Produces',
                'ordering': ['-listed_at'],
            },
        ),
    ]
