# Generated by Django 5.1.7 on 2025-04-05 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uzhavan_hub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produce',
            name='approved',
        ),
    ]
